language: en-US
issue_enrichment:
  auto_enrich:
    enabled: false
reviews:
  profile: assertive

  # Suppress redundant posts and collapse the "walkthrough" post
  review_status: false          # removes the "Actions performed" status comment
  in_progress_fortune: false    # removes the in-progress "Currently processing…" comment
  collapse_walkthrough: true

  # Don't edit the PR top post
  high_level_summary_in_walkthrough: true

  # Remove mostly redendant/noisy sections
  sequence_diagrams: false
  suggested_labels: false
  changed_files_summary: false
  poem: false

  # disable suggesting tasks for coderabbit
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  # disable docstring coverage checks
  pre_merge_checks:
    docstrings:
      mode: off

  # Focus reviews on changed code only
  path_instructions:
    - path: "**"
      instructions: |
        Only review what changed in this PR (added/modified lines and their immediate context).
        Do not flag pre-existing issues unless they are correctness, crash, or security risks.
        If you notice repo-wide improvement opportunities, summarize them under a single
        collapsed "Non‑blocking: repo‑wide observations" section in the walkthrough; avoid inline comments for these.
