#!/bin/bash

export tmpdir="/tmp/ulauncher_deb"
export tmpsrc="$tmpdir/src"
rm -rf $tmpdir
mkdir -p $tmpsrc
cp -r {AUTHORS,bin,data,debian,LICENSE,README.md,setup.cfg,setup.py,ulauncher,ulauncher.desktop.in,ulauncher_lib} $tmpsrc
cd $tmpsrc
dpkg-buildpackage -tc -S -sa -k$GPGKEY

echo "RUN: cd $tmpdir"
