FROM archlinux/base

MAINTAINER ulauncher.app@gmail.com

RUN useradd -ms /bin/sh kenny && \
    pacman --noconfirm -Syu && \
    pacman --noconfirm -S binutils python2 git grep openssh

WORKDIR /home/kenny/ulauncher
USER kenny
