FROM fedora:25

MAINTAINER ulauncher.app@gmail.com

WORKDIR /root/ulauncher

RUN dnf install -y \
        gcc \
        make \
        rpm-build \
        python3-devel \
        rsync \
        intltool \
        python3-distutils-extra && \
    curl https://bootstrap.pypa.io/ez_setup.py | python
