# NOTE: These scripts are intended to run very fast , not to become frustrating,
# pytest was the clear bottleneck (and can't check only staged files), so it was not included.

skip_lfs = true

[pre-commit]
# make sure to only run one job with stage_fixed, or disable parallel
# otherwise one job might might overwrite the changes of another job
# and jobs can fail because a previous job created the git lockfile,
parallel = true

[pre-commit.commands.typos]
glob = "*"
run = "typos --force-exclude {staged_files}"

[pre-commit.commands.ruff]
glob = "*.py"
run = """
  ruff check --fix {staged_files}
  ruff format {staged_files}
  """
stage_fixed = true

[pre-commit.commands.mypy]
root = "ulauncher"
glob = "*.py"
# counter-intuitive, but need to exclude the interfaces module (if staged), or the actual
# type (inside the pyi) will fail to load by the other staged files
exclude = "interfaces.py"
run = "mypy {staged_files}"
