#!/usr/bin/env bash

# Implements the build and packaging commands. The makefile is the front door for them,
# and the release scripts below call each other through this file.

. scripts/common.sh
. scripts/init-dev-env.sh
. scripts/cleanup-dev-env.sh
. scripts/dev-container.sh
. scripts/build-deb.sh
. scripts/build-rpm.sh
. scripts/build-targz.sh
. scripts/build-doc.sh
. scripts/build-preferences.sh
. scripts/build-release.sh
. scripts/watch-doc.sh


main () {
  case "$1" in
    init-dev-env) init-dev-env ;;
    cleanup-dev-env) cleanup-dev-env ;;
    dev-container) dev-container $2 ;;
    build-deb) build-deb $2 $3 ;;
    build-rpm) build-rpm $2 $3 $4 ;;
    build-targz) build-targz $2 ;;
    build-doc) build-doc ;;
    build-preferences) build-preferences $2 ;;
    build-release) build-release $2 ;;
    upload-release) upload-release $2 ;;
    watch-doc) watch-doc ;;

    # Undocumented aliases for the commands that moved to the makefile, so anything
    # still calling them (packaging scripts) keeps working
    run) exec make run ARGS="${*:2}" ;;
    rm-python-cache) exec make rm-python-cache ;;
    test-mypy) exec make mypy ;;
    test-pylint) exec make pylint ;;
    test-flake8) exec make flake8 ;;
    test-pytest) exec make pytest ;;
    test) exec make check ;;
    send-signal) exec make send-signal SIGNAL="$2" ;;
    edit-ui) exec make edit-ui FILE="$2" ;;

    *)
      echo "${red}[!] Unrecognized command '${1}'${normal}"
      usage
      exit 1
      ;;
  esac
}

usage () {
  echo "Run '${bold}make${normal}' for the list of commands"
}

if [ $# -eq 0 ]; then
  usage
  exit 1
else
  main $@
fi
