FROM fedora:30

MAINTAINER ulauncher.app@gmail.com

WORKDIR /root/ulauncher

# Python 3.7.5
RUN dnf install -y \
        gcc \
        make \
        rpm-build \
        python3-devel \
        rsync \
        intltool \
        python3-distutils-extra \
        python3-setuptools
