FROM fedora:31

MAINTAINER ulauncher.app@gmail.com

WORKDIR /root/ulauncher

RUN dnf install -y \
        gcc \
        make \
        rpm-build \
        python3-devel \
        rsync \
        intltool \
        python3-distutils-extra \
        python3-setuptools
