FROM opensuse:42.3

MAINTAINER ulauncher.app@gmail.com

WORKDIR /root/ulauncher

# Python 3.4.6
RUN zypper install -y \
        gcc \
        make \
        rpm-build \
        python3-devel \
        rsync \
        intltool \
        python3-distutils-extra \
        python3-setuptools
