name: Bug Report
description: Report a bug in Ulauncher.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your Linux distro, desktop environment and other relevant information for reproducing the issue.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What did you do to trigger the issue? What happened, and what did you expected to happen instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Run Ulauncher from the shell with `ulauncher -v` and copy and paste the log output or grab the log from the previous session (`~/.local/share/ulauncher/last.log` for v5 or `~/.local/state/ulauncher/last.log` for v6). This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: communication-guidelines
    attributes:
      label: Communication guidelines
      description: Did you read the [communication guidelines](https://github.com/Ulauncher/Ulauncher/blob/dev/CODE_OF_CONDUCT.md#general-communication-guidelines) and [troubleshooting page](https://github.com/Ulauncher/Ulauncher/discussions/991)?
      options:
        - label: I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
          required: true
  - type: checkboxes
    id: no-extension
    attributes:
      label: Not an extension issue
      description: Ulauncher does not support or maintain third party extensions. If you have issues with extensions you should read and follow their dependency installation instructions and file any issues on their issue trackers.
      options:
        - label: This issue applies to the Ulauncher application, not a specific extension.
          required: true
  - type: checkboxes
    id: latest
    attributes:
      label: Ulauncher v6
      description: Please test with the [Ulauncher v6 branch](https://github.com/Ulauncher/Ulauncher/issues/869) or at least read through this post to ensure the bug hasn't already been fixed. Ulauncher v6 doesn't have a release yet, but it's miles ahead of v5.
      options:
        - label: I have made sure the bug isn't already fixed in v6.
          required: true
