extend = "../../pyproject.toml"

# override the gi and ui ban, while preserving all other ban rules
[lint.flake8-tidy-imports.banned-api]
"functools.lru_cache" = {msg = "Use ulauncher.utils.lru_cache instead to preserve parameter types."}
"functools.cache" = {msg = "Use ulauncher.utils.lru_cache instead to preserve parameter types."}
"functools.cached_property" = {msg = "cached_property erases property types. If you need to use this, create a typed wrapper similar to ulauncher.utils.lru_cache"}
