# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-


# DO NOT EDIT THIS FILE

"""Helpers for an Ubuntu application."""
import logging
import os

from ulauncher_lib.ulauncherconfig import get_data_file
from ulauncher_lib.Builder import Builder
from gi.repository import GdkPixbuf

from .lru_cache import lru_cache
from .run_async import run_async
from locale import gettext as _
from xdg.BaseDirectory import xdg_config_home
from distutils.dir_util import mkpath


def get_builder(builder_file_name):
    """Return a fully-instantiated Gtk.Builder instance from specified ui
    file

    :param builder_file_name: The name of the builder file, without extension.
        Assumed to be in the 'ui' directory under the data path.
    """
    # Look for the ui file that describes the user interface.
    ui_filename = get_data_file('ui', '%s.ui' % (builder_file_name,))
    if not os.path.exists(ui_filename):
        ui_filename = None

    builder = Builder()
    builder.set_translation_domain('ulauncher')
    builder.add_from_file(ui_filename)
    return builder


# Owais Lone : To get quick access to icons and stuff.
def get_media_file(media_file_name):
    media_filename = get_data_file('media', '%s' % (media_file_name,))
    if not os.path.exists(media_filename):
        media_filename = None

    return "file:///" + media_filename


class NullHandler(logging.Handler):
    def emit(self, record):
        pass


def set_up_logging(opts):
    # add a handler to prevent basicConfig
    root = logging.getLogger()
    null_handler = NullHandler()
    root.addHandler(null_handler)

    formatter = logging.Formatter("%(asctime)s:%(levelname)s:%(name)s: %(funcName)s() '%(message)s'")

    logger = logging.getLogger('ulauncher')
    logger_sh = logging.StreamHandler()
    logger_sh.setFormatter(formatter)
    logger.addHandler(logger_sh)

    logger.debug('testing...')

    lib_logger = logging.getLogger('ulauncher_lib')
    lib_logger_sh = logging.StreamHandler()
    lib_logger_sh.setFormatter(formatter)
    lib_logger.addHandler(lib_logger_sh)

    logger.setLevel(logging.INFO)

    # Set the logging level to show debug messages.
    if opts.verbose:
        logger.setLevel(logging.DEBUG)
        logger.debug('logging enabled')
    if opts.verbose > 1:
        lib_logger.setLevel(logging.DEBUG)

    # set up login to a file
    log_file = os.path.join(get_config_dir(), 'last.log')
    if os.path.exists(log_file):
        os.remove(log_file)

    file_handler = logging.FileHandler(log_file)
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    lib_logger.addHandler(file_handler)


def alias(alternative_function_name):
    '''see http://www.drdobbs.com/web-development/184406073#l9'''
    def decorator(function):
        '''attach alternative_function_name(s) to function'''
        if not hasattr(function, 'aliases'):
            function.aliases = []
        function.aliases.append(alternative_function_name)
        return function
    return decorator


def get_config_dir():
    config_dir = os.path.join(xdg_config_home, 'ulauncher')

    if not os.path.exists(config_dir):
        mkpath(config_dir)

    return config_dir


@lru_cache(maxsize=50)
def load_image(path, size):
    """
    Return Pixbuf instance
    """
    return GdkPixbuf.Pixbuf.new_from_file_at_size(path, size, size)


def recursive_search(rootdir='.', suffix=''):
    """
    Search files recursively in rootdir
    """
    suffix = suffix.lower()
    return [os.path.join(looproot, filename)
            for looproot, _, filenames in os.walk(rootdir)
            for filename in filenames if filename.lower().endswith(suffix)]
